name: rottentoriches
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - playwright
    - scikit-learn
    - xgboost
    - nltk
    - kalshi-python
    - python-dotenv
    - cryptography

